networks:
  backend:
    driver: bridge

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always

  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    image: postgres
    networks:
      - backend
    ports:
      - 5432:5432
    restart: always

  web:
    command: go run server.go
    depends_on:
      - db
    image: golang
    networks:
      - backend
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
